### ISSUE TITLE
Issue with loading data. Possibly Cors

### ISSUE THREAD

**Issue by PermanAtayev** [iVis-at-Bilkent/cytoscape-web-service#16]

**Comment by hasanbalci** [comment]
@PermanAtayev I just made a simple commit (3b8d42517e8c6b255a159e406bcba0f1bc8154b6) and then try to deploy in Heroku again, but it gave Cors error. Do you have any idea why it is? I think I did something wrong or skipped a point during deloyment.

**Comment by PermanAtayev** [comment]
I don't have an idea, but I can check it out

**Comment by PermanAtayev** [comment]
@hasanbalci there was another issue apparently with cors, it is fixed now.
