### ISSUE TITLE
Demo client improvements

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape-web-service#3]
- [x] 1. Samples should include nodes with non-uniform node dimensions
- [x] 2. Do not use "compoundless" in file names, etc. (graph without compounds = simple graph)
- [x] 3. SBGN-ML samples do include compounds, name them in the menu accordingly. Note that SBGN-ML has a built-in mechanism for representing compounds
- [x] 4. Cytoscape.js Layout Demo -> Cytoscape.js Layout Service Demo
- [x] 5. Change selection color to be non black & white so it's better visible (cyan?).
- [x] 6. Doesn't look like node dimensions are actually taken into account in some samples/layout styles (e.g. sample12-clustered-graphml.txt and CiSE, sample3-simple-graphml.txt and CoSE-bilkent)
- [x] 7. I don't think node dimensions are properly taken into account with CiSE. Change node separation to 10 in sample11 and you get the following. There should not be any overlap even with node separation set to 0.
![network (1)](https://user-images.githubusercontent.com/3874988/62054042-7c43e500-b221-11e9-82d7-6ef18c6538b2.png)
- [x] 8. Doesn't look like CoSE-Bilkent is working properly with disconnected nodes. See sample8; one of the two smaller compounds contains 2 disconnected nodes, and they seem to be placed on top of each other (drag one to see this).

**Comment by PermanAtayev** [comment]
@ugurdogrusoz I think all issues are fixed now, can you please check

**Comment by ugurdogrusoz** [comment]
1. I think we need
- more non-uniformity in node dimensions (number of samples with non-uniform node dimensions should be increased AND the uniformity of the node dimensions should be increased)
- at least some graphs to be larger (# of nodes/edges). n = 100 or so for instance
- samples 4, 5 & 6 look same to me
- do not use too many samples that are disconnected (multiple components)
5. Let's use border color for selection purposes in nodes (background color represents clusters in some graphs). I would use the same selection color that we use for nodes for edges as well (instead of green).

**Comment by PermanAtayev** [comment]
@ugurdogrusoz I think I fixed issues 1 and 5, can you please check?

**Comment by PermanAtayev** [comment]
@ugurdogrusoz about the graph no 18, it is really huge. That's why it will take some time to open it

**Comment by PermanAtayev** [comment]
@ugurdogrusoz Can you please also check the 6th issue, there seems to be no issue. To test it I changed dimensions of some nodes in those 3rd and 12th samples.

**Comment by ugurdogrusoz** [comment]
- Regarding 1, please change sample names from "huge" to "big" for samples 5 & 6 (huge is typically thousands of nodes in a graph).
- Regarding 1, I see disconnected gray nodes at the bottom touching each other in sample 15 with cose-bilkent. That should not happen:
![image](https://user-images.githubusercontent.com/3874988/61938916-d67f4480-af9a-11e9-919a-16b7206ccc03.png)

- Regarding 5, what I meant was selection should not change the background color of nodes since background color signifies clusters. Instead it should only change the border color.
![image](https://user-images.githubusercontent.com/3874988/61938241-4ab8e880-af99-11e9-9f6a-4afa3e3ed475.png)

**Comment by PermanAtayev** [comment]
I fixed 1st and 5th issues, can you please check them?

**Comment by ugurdogrusoz** [comment]
5. We should use the same selection color (cyan) for nodes and edges :)

**Comment by PermanAtayev** [comment]
@ugurdogrusoz the selection color is updated:)

**Comment by PermanAtayev** [comment]
@ugurdogrusoz 
I fixed 7th and 8th sub-issues, can you please check them?

1st and 16th examples are good for seeing the fix.
