### ISSUE TITLE
About dialog

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape-web-service#6]
Let's have a minimal About dialog under Help. That is, turn help into a menu with menu items:
- Quick Help: current Help content
- About
Title of the dialog: About
Content (should be center justified):
Cytoscape.js Layout Service Demo 1.0

i-Vis information Visualization Lab
Bilkent University, Ankara, Turkey

https://github.com/iVis-at-Bilkent/cytoscape.js-layout-service

**Comment by PermanAtayev** [comment]
@ugurdogrusoz Can you please check it now?

**Comment by ugurdogrusoz** [comment]
- Let's remove the bold face except the first line "Cytoscape.js ..."
- Let's fix the typo: "information" -> "Information"
Quick Help related:
- "File | Load ... :" -> "File | Load...:"
- "
- Add the following to the end:
    Layout | Style | ...: Change layout style
    Layout | Perform Layout: Apply the current layout style to the current graph
    Layout | Layout Properties...: Change layout options for the current layout style
- Let's also change "xxx ..." to "xxx..." in our menus.

**Comment by PermanAtayev** [comment]
The dialog is improved, can you please check it? @ugurdogrusoz
