### ISSUE TITLE
Upgrade Cytoscape.js and any extensions, libraries used

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape-web-service#7]
We should use the latest of all unless there is a good reason not to.

**Comment by PermanAtayev** [comment]
Cytoscape, extensions, libraries are upgraded. Since the jQuery update was huge, I also inserted a migration tool to help fix problems. You can go to Github to see the versions of the front-end tools used. @ugurdogrusoz

**Comment by ugurdogrusoz** [comment]
Assuming the Heroku deployment up to date, things look fine, closing the issue.
