### ISSUE TITLE
Remove unused, nonworking functionality

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape-web-service#8]
Let get rid of the following from the menu:
- Undo/Redo (was this working before?)
- View menu all together (Expand/Collapse)

**Comment by PermanAtayev** [comment]
I am not sure about Expand/Collapse, but Undo/Redo was working. I will check it out.

**Comment by ugurdogrusoz** [comment]
- I don't see undo-redo extension in package.json. It'd be nice to get that working.
- Don't worry about expand/collapse, and just remove it since its inclusion could create problems with layout.

**Comment by PermanAtayev** [comment]
You won't be able to see it in the package.json, because I keep back-end and front-end separately. But when it will be there you will be able to see it in the index.html's dependencies.

**Comment by ugurdogrusoz** [comment]
Undo - redo is partially working. For instance, it works for dragging nodes but not for adding nodes.

**Comment by PermanAtayev** [comment]
I see. I will fix it.

**Comment by PermanAtayev** [comment]
@ugurdogrusoz I think that the undo/redo is working properly now. Can you please take a look at it?

**Comment by ugurdogrusoz** [comment]
Seems fine now, thanks!
