### ISSUE TITLE
Save-file isn't working. Add json, graphml(optional)

### ISSUE THREAD

**Issue by PermanAtayev** [iVis-at-Bilkent/cytoscape-web-service#9]

**Comment by PermanAtayev** [comment]
also update the help, in case you can save the graph in json format as well

**Comment by PermanAtayev** [comment]
@ugurdogrusoz I added the save as JSON option. Later on I can add the graphml one, but do we need it?

**Comment by ugurdogrusoz** [comment]
Let's save it as JSON only but I would put it right below "Load..." as "Save", not with PNG save.

**Comment by PermanAtayev** [comment]
@ugurdogrusoz I updated the menu. Can you please take a look?

**Comment by ugurdogrusoz** [comment]
Seems to work fine but I noticed that I don't see any new line characters (neither of WordPad and Notepad on Windows) in the file, which makes it difficult to read. Any chance it can be formatted to be easier to read (by humans)?

**Comment by PermanAtayev** [comment]
I think it is about the file-saver I am using. I will see what can be done.

**Comment by PermanAtayev** [comment]
@ugurdogrusoz JSON file seems to be readable now. Can you please check it?
